### ISSUE TITLE
Test if user can upload data to jupyter instance

### ISSUE THREAD

**Issue by minump** [ncsa/cyber2a-workshop#20]
Loggin to cyber2a.software with user credentials (user01, user50). Test if user can upload data (foundaiton_models/data/docs. or data/images)

**Comment by minump** [comment]
Tested in foundaiton/data/docs and foundation_models/data/images. with username "user01" .. able yo upload data.
Can close once Sandeep has tested.

**Comment by sandeep-ps** [comment]
Tested and closing.
